# Generated by Django 4.2.7 on 2024-05-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='jobs', verbose_name='Photo'),
        ),
    ]
